image: ubuntu

build_script:
  - sh: dotnet test /home/appveyor/projects/masked-emails-inboxapi/src/InboxApi.Tests/
  - sh: dotnet publish -c Release /home/appveyor/projects/masked-emails-inboxapi/src/InboxApi --self-contained --runtime linux-x64 --output ./output/

after_build:
  - 7z a ./artifacts/archive.zip ./output/

artifacts:
  - path: artifacts/archive.zip
    name: archive
    type: file

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: Masked Emails Inbox API
    auth_token:
      secure: QxXD5boO1cRwZNpg17XsXqC1kxznj5IhNa1m4TvpuUzl6BSErb99eM0+wMbE5dv8
    artifact: /.*\.(zip)$/
    prerelease: true
    on:
      branch: main # only release from master branch
      APPVEYOR_REPO_TAG: true # only release on new tag