version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /etc/nginx/conf.d:/etc/nginx/conf.d
    - /etc/certbot/conf:/etc/letsencrypt
    - /etc/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
    - /etc/certbot/conf:/etc/letsencrypt
    - /etc/certbot/www:/var/www/certbot

  inbox:
    image: springcomp/masked-emails-inbox-api:latest
    hostname: inbox
    domainname: masked-emails
    container_name: inbox
    volumes:
    - /var/mail/:/var/mail/
    restart: unless-stopped
